# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Prix unitaire HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Prix unitaire TTC')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Attribut',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Position')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iottestnca_Application.ProductAttribute', verbose_name=b'Unit\xc3\xa9')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Valeur attribut',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_ean13', models.CharField(max_length=13)),
                ('attributes', models.ManyToManyField(blank=True, null=True, related_name='product_item', to='iottestnca_Application.ProductAttributeValue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iottestnca_Application.Product')),
            ],
            options={
                'verbose_name': 'D\xe9clinaison Produit',
            },
        ),
    ]
