# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import iottestnca_Application.extras


class Migration(migrations.Migration):

    dependencies = [
        ('iottestnca_Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'dm', help_text=b'Sch\xc3\xa9ma JSON du datamodel', max_length=250, unique=True, verbose_name=b'Name')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Date de cr\xc3\xa9ation')),
                ('file', models.FileField(upload_to=b'documents/%Y/%m/%d', validators=[iottestnca_Application.extras.validate_file_extension_docs])),
            ],
            options={
                'verbose_name': 'Datamodel ',
                'verbose_name_plural': 'Datamodels ',
            },
        ),
    ]
