# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iottestnca_Application', '0002_datamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='name',
            field=models.CharField(default=b'Datamodel-NCA-[Identifiant]', help_text=b'Sch\xc3\xa9ma JSON du datamodel', max_length=250, unique=True, verbose_name=b'Name'),
        ),
    ]
