# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iottestnca_Application.extras


class Migration(migrations.Migration):

    dependencies = [
        ('iottestnca_Application', '0003_auto_20171024_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Source-NCA-[Identifiant]', help_text='Source en xml | json | txt | csv', max_length=250, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('file', models.FileField(upload_to='documents/sources/%Y/%m/%d', validators=[iottestnca_Application.extras.validate_file_extension_docs])),
            ],
            options={
                'verbose_name': 'Source NCA ',
                'verbose_name_plural': 'Sources NCA ',
            },
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[iottestnca_Application.extras.validate_file_extension_docs]),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='name',
            field=models.CharField(default='Datamodel-NCA-[Identifiant]', help_text='Schéma JSON du datamodel', max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire TTC'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iottestnca_Application.ProductAttribute', verbose_name='Unité'),
        ),
    ]
