# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import iottestnca_Application.extras


class Migration(migrations.Migration):

    dependencies = [
        ('iottestnca_Application', '0004_auto_20171024_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceNCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Source-NCA-[Identifiant]', help_text='Source en xml | json | txt | csv', max_length=250, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('json', models.FileField(upload_to='documents/sources/%Y/%m/%d', validators=[iottestnca_Application.extras.validate_file_extension_json])),
                ('otherFormat', models.FileField(upload_to='documents/sources/%Y/%m/%d', validators=[iottestnca_Application.extras.validate_file_extension_docs])),
            ],
            options={
                'verbose_name': 'Source NCA ',
                'verbose_name_plural': 'Sources NCA ',
            },
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
